
create extension if not exists pgcrypto;

create table if not exists public.plx_projects (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid references auth.users(id) on delete cascade,
  title text not null,
  slug text not null,
  engine text not null,
  manifest jsonb not null default '{}'::jsonb,
  style_dna jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  thumbnail_url text,
  remix_parent_id uuid references public.plx_projects(id) on delete set null,
  remix_allowed boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(creator_id, slug)
);

create table if not exists public.plx_versions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.plx_projects(id) on delete cascade,
  manifest jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.plx_assets (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.plx_projects(id) on delete cascade,
  role text not null,
  storage_path text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.plx_plays (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.plx_projects(id) on delete cascade,
  player_id uuid references auth.users(id) on delete set null,
  completed boolean not null default false,
  score integer,
  duration_ms integer,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id,name,public)
values ('plx-media','plx-media',false)
on conflict (id) do nothing;

alter table public.plx_projects enable row level security;
alter table public.plx_versions enable row level security;
alter table public.plx_assets enable row level security;
alter table public.plx_plays enable row level security;

drop policy if exists "published projects public read" on public.plx_projects;
create policy "published projects public read" on public.plx_projects for select using (status='published' or auth.uid()=creator_id);

drop policy if exists "creator owns projects" on public.plx_projects;
create policy "creator owns projects" on public.plx_projects for all using (auth.uid()=creator_id) with check (auth.uid()=creator_id);

drop policy if exists "creator reads project versions" on public.plx_versions;
create policy "creator reads project versions" on public.plx_versions for all
using (exists(select 1 from public.plx_projects p where p.id=project_id and p.creator_id=auth.uid()))
with check (exists(select 1 from public.plx_projects p where p.id=project_id and p.creator_id=auth.uid()));

drop policy if exists "creator assets" on public.plx_assets;
create policy "creator assets" on public.plx_assets for all
using (exists(select 1 from public.plx_projects p where p.id=project_id and p.creator_id=auth.uid()))
with check (exists(select 1 from public.plx_projects p where p.id=project_id and p.creator_id=auth.uid()));

drop policy if exists "plays insert" on public.plx_plays;
create policy "plays insert" on public.plx_plays for insert with check (true);
