const PROFILES={
  runner:{camera:'side-scrolling / on-rails forward movement',loop:'continuous forward movement, jump/slide/dodge timing, escalating hazards and collectibles',scroll:'world moves left while the player advances right',art:'layered arcade environment with readable foreground hazards and speed FX'},
  dodge:{camera:'top-down / forward-motion dodge view',loop:'free lateral movement while hazards enter from ahead and travel toward the player',scroll:'environment moves downward toward the player',art:'high-contrast lanes, themed hazards, pickups and warning FX'},
  collect:{camera:'top-down exploration',loop:'explore, identify themed collectibles, gather them, avoid contextual hazards and complete a collection goal',scroll:'camera follows player movement naturally; no fake auto-scroll',art:'dense themed world props, landmarks, collectibles and environmental storytelling'},
  rhythm:{camera:'front-facing rhythm arcade view',loop:'incoming beat cues descend toward timing zones while character reacts to accurate hits and misses',scroll:'rhythm field and ambience move downward with incoming notes',art:'music-reactive lighting, themed note assets, stage FX and combo feedback'},
  puzzle:{camera:'fixed puzzle board',loop:'read visual clues, manipulate themed objects, solve pattern/memory/spatial challenge',scroll:'static environment; animate only puzzle feedback and ambience',art:'clean tactile themed pieces rather than generic blocks'},
  fps:{camera:'first-person arcade shooter',loop:'aim, fire, reload, prioritize targets, survive waves and clear the objective',scroll:'no arbitrary background scrolling; camera/target motion provides movement',art:'themed enemies, weapon, crosshair, muzzle/hit FX, cover and depth layers'},
  fighting:{camera:'side-view 1v1 arcade fighter',loop:'move, jump, attack, block, react, build pressure and defeat the rival',scroll:'stage remains spatially stable; camera follows fighter spacing instead of auto-scrolling',art:'full rival character, readable arena floor, impact FX, life bars and stage props'},
  openworld:{camera:'free-roam top-down / 2.5D exploration',loop:'travel between landmarks, interact with NPCs, collect objectives and discover environmental events',scroll:'camera follows the player through a larger world in the direction of movement',art:'district-specific buildings, props, NPCs, roads, landmarks and quest objects'},
  racing:{camera:'behind/top-down arcade racing',loop:'steer through traffic, collect boosts, avoid collisions and reach the finish',scroll:'road and scenery move downward toward the player to communicate forward speed',art:'real vehicles, road markings, barriers, boosts, traffic and motion FX'},
  platformer:{camera:'side-scrolling platformer',loop:'run, jump, land, climb and avoid enemies while progressing toward a visible goal',scroll:'world moves left as the player/camera advances right',art:'themed platforms, enemies, collectibles, vegetation/props and depth layers'}
};

function clean(s=''){return String(s).trim().replace(/\s+/g,' ');}
function inferEngine(prompt=''){const p=prompt.toLowerCase();const tests=[['fps',/fps|first person|shooter|shoot|target/],['fighting',/fight|fighting|boxing|duel|versus|1v1/],['racing',/race|racing|drive|driving|vehicle|car/],['rhythm',/rhythm|dance|beat|music|tempo/],['puzzle',/puzzle|match|memory|solve|sequence/],['openworld',/open world|free roam|sandbox|quest|explore city/],['platformer',/platform|jump across|side scroll/],['dodge',/dodge|avoid|falling|escape/],['collect',/collect|gather|find|hunt|relic/]];for(const [e,r] of tests)if(r.test(p))return e;return 'runner';}
function cap(s=''){return s?s[0].toUpperCase()+s.slice(1):s;}

export function calibratePromptLocal({prompt='',engine='runner',style='premium arcade',sourceSummary=''}){
  engine=engine||inferEngine(prompt);
  const p=PROFILES[engine]||PROFILES.runner;
  const idea=clean(prompt)||'Create a playable experience inspired by the uploaded media.';
  return `Create a polished ${style} ${engine.toUpperCase()} PLX from the uploaded media.\n\nCORE IDEA\n${cap(idea)}\n\nGAMEPLAY INTERPRETATION\n- Camera: ${p.camera}.\n- Core loop: ${p.loop}.\n- World motion: ${p.scroll}.\n- Make the first meaningful interaction happen within 3–5 seconds.\n- Build clear escalation, a mid-game visual event, and a satisfying finish state.\n\nSOURCE-MEDIA RULES\n- Identify the primary subject separately from large background objects before creating the player.\n- Use the uploaded media as visual DNA, not as a flat full-screen background.\n- Extract or reinterpret recognizable objects as gameplay assets only when their masks are clean.\n- If extraction quality is weak, replace the object with a polished themed asset instead of a black square, crude crop, or geometric placeholder.\n${sourceSummary?`- Source analysis: ${sourceSummary}.\n`:''}\nART DIRECTION\n- ${p.art}.\n- Build far, mid, near and gameplay layers with correct movement for this game type.\n- Preserve the source palette, mood and recognizable visual motifs while unifying everything into one arcade art style.\n- Use readable silhouettes, clean transparent edges, dimensional lighting, particles, impact feedback and premium HUD treatment.\n- Never use plain black rectangles/squares as visible gameplay art.\n\nQUALITY BAR\nThe result should look like a finished arcade mini-game, not a prototype, debug test, or image placed behind moving shapes.`;
}
