import Phaser from 'phaser';
import { BasePLXScene } from './BasePLXScene.js';
import { AnimationDirector } from '../animation/AnimationDirector.js';

export class FPSScene extends BasePLXScene{
  constructor(manifest){super('FPSScene',manifest)}
  create(){
    this.makeParallaxBackground({speed:0});const wk=this.manifest.worldKit||{};this.enemyKeys=wk.enemyKeys||['enemy'];this.propKeys=wk.propKeys||[];
    // Pseudo-3D runway perspective + terminal cover makes the scene read as a place, not a flat poster.
    const g=this.add.graphics().setDepth(2);g.fillStyle(0x101923,.82);g.beginPath();g.moveTo(250,600);g.lineTo(420,225);g.lineTo(540,225);g.lineTo(720,600);g.closePath();g.fillPath();g.lineStyle(3,0xffffff,.22);for(let i=0;i<7;i++){const t=i/7,y=255+t*t*330,w=20+t*110;g.lineBetween(480-w,y,480+w,y);}g.lineStyle(2,0x24c9c5,.28);g.lineBetween(420,225,250,600);g.lineBetween(540,225,720,600);
    for(let i=0;i<10;i++){const key=this.propKeys[i%this.propKeys.length];if(key&&this.textures.exists(key)){const side=i%2?-1:1,depth=i/10,scale=.25+depth*.55,x=480+side*(150+depth*300),y=285+depth*255;this.add.image(x,y,key).setScale(scale).setAlpha(.75).setDepth(5+Math.floor(depth*10));}}
    this.add.rectangle(480,575,960,120,0x081523,.88).setDepth(40);this.weapon=this.add.image(480,548,'weapon').setScale(.72).setDepth(45);this.crosshair=this.add.image(480,285,'crosshair').setScale(.55).setDepth(100);AnimationDirector.idleSway(this,this.crosshair);this.input.on('pointermove',p=>this.crosshair.setPosition(p.x,p.y));this.input.on('pointerdown',p=>this.fire(p.x,p.y));this.keys=this.input.keyboard.addKeys('R');this.enemies=[];this.health=100;this.ammo=12;this.reserve=48;this.elapsed=0;this.spawnClock=0;this.reloading=false;this.wave=1;this.kills=0;this.eliteEvery=6;this.signatureTriggered=false;
    this.makeHUD();this.healthText=this.add.text(22,52,'HEALTH 100',{fontFamily:'Arial',fontSize:'18px',fontStyle:'bold',color:'#ffffff'}).setDepth(100);this.ammoText=this.add.text(938,52,'AMMO 12 / 48',{fontFamily:'Arial',fontSize:'18px',fontStyle:'bold',color:'#24c9c5'}).setOrigin(1,0).setDepth(100);this.missionText=this.add.text(480,20,'MISSION: CLEAR THE APPROACH',{fontFamily:'Arial',fontSize:'17px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5,0).setDepth(100);
    for(let i=0;i<7;i++){const l=this.add.circle(190+i*90,225,3,0x24c9c5,.6).setDepth(20);this.tweens.add({targets:l,alpha:.08,duration:500+i*90,yoyo:true,repeat:-1});}
  }
  reload(){if(this.reloading||this.ammo===12||this.reserve<=0)return;this.reloading=true;this.ammoText.setText('RELOADING...');this.tweens.add({targets:this.weapon,y:610,angle:-12,duration:280,yoyo:true,hold:210,onComplete:()=>{const need=12-this.ammo,take=Math.min(need,this.reserve);this.ammo+=take;this.reserve-=take;this.reloading=false;this.updateAmmo();}})}
  updateAmmo(){this.ammoText.setText(`AMMO ${this.ammo} / ${this.reserve}`)}
  fire(x,y){if(this.finished||this.reloading)return;if(this.ammo<=0){this.reload();return;}this.ammo--;this.updateAmmo();this.tweens.killTweensOf(this.weapon);this.weapon.setY(548).setAngle(0);this.tweens.add({targets:this.weapon,y:558,angle:Phaser.Math.Between(-2,2),duration:45,yoyo:true});this.cameras.main.flash(26,255,245,220,false);let target=null,best=9999;for(const e of this.enemies){if(!e.active)continue;const d=Phaser.Math.Distance.Between(x,y,e.x,e.y);if(d<58*e.scaleX&&d<best){best=d;target=e;}}if(target){this.kills++;this.setScore(this.score+(target.elite?300:100));const fx=this.add.image(target.x,target.y,'hitfx').setScale(target.scaleX*.55).setDepth(95).setAlpha(.95);this.tweens.add({targets:fx,scaleX:fx.scaleX*1.8,scaleY:fx.scaleY*1.8,alpha:0,duration:180,onComplete:()=>fx.destroy()});target.destroy();this.enemies=this.enemies.filter(e=>e!==target);}else this.setScore(Math.max(0,this.score-5));}
  spawnEnemy(forcedIndex=null){const lane=Phaser.Math.Between(0,4),startX=[145,310,480,650,815][lane],idx=forcedIndex??((this.kills+this.enemies.length)%this.enemyKeys.length),key=this.enemyKeys[idx%this.enemyKeys.length]||'enemy';const e=this.add.image(startX,160+Phaser.Math.Between(-25,25),key).setScale(.20).setDepth(10);e.elite=idx%3===2;e.depthZ=0;e.advance=(e.elite?.0012:.00086)+Math.random()*.0005;e.drift=(Math.random()-.5)*.5;if(e.elite)e.setTint(0xffd95a);this.enemies.push(e);}
  signatureWave(){if(this.signatureTriggered)return;this.signatureTriggered=true;this.missionText.setText('SIGNATURE WAVE — HOLD THE RUNWAY');this.cameras.main.shake(220,.006);for(let i=0;i<6;i++)this.time.delayedCall(i*260,()=>this.spawnEnemy(i%3));this.time.delayedCall(3400,()=>this.missionText.setText('MISSION: CLEAR THE APPROACH'));}
  update(_,dt){if(this.finished)return;this.elapsed+=dt;this.spawnClock+=dt;if(Phaser.Input.Keyboard.JustDown(this.keys.R))this.reload();if(this.spawnClock>Math.max(500,1050-this.elapsed/110)){this.spawnClock=0;this.spawnEnemy();}if(this.elapsed>14000&&!this.signatureTriggered)this.signatureWave();for(const e of [...this.enemies]){e.depthZ+=e.advance*dt;e.x+=e.drift*dt*.08;const s=.20+e.depthZ*1.28;e.setScale(s);e.y=165+e.depthZ*305;e.setDepth(10+Math.floor(e.depthZ*20));if(e.depthZ>1){e.destroy();this.enemies=this.enemies.filter(x=>x!==e);this.health=Math.max(0,this.health-20);this.healthText.setText(`HEALTH ${this.health}`);this.cameras.main.shake(130,.012);if(this.health<=0){this.win('MISSION FAILED');return;}}}if(this.elapsed>(this.manifest.duration||42)*1000)this.win('MISSION COMPLETE');}
}
