import Phaser from 'phaser';
import { BasePLXScene } from './BasePLXScene.js';

export class PuzzleScene extends BasePLXScene{
  constructor(m){super('PuzzleScene',m)}
  create(){
    this.makeParallaxBackground();this.makeHUD();this.goalText.setText('MATCH 3 · TARGET 2500');
    this.rows=8;this.cols=8;this.cell=52;this.boardX=276;this.boardY=104;this.types=[0,1,2,3,4,5];this.colors=[0xff5d7d,0x6c63ff,0x2ad5c8,0xffcc4d,0xff8a4c,0x7ed957];this.grid=[];this.selected=null;this.busy=false;
    this.add.rectangle(480,305,470,470,0x091b2c,.92).setStrokeStyle(4,0x2ad5c8,.55).setDepth(1);
    for(let r=0;r<this.rows;r++){this.grid[r]=[];for(let c=0;c<this.cols;c++){let t=this.randomTypeAvoidingMatch(r,c);this.grid[r][c]=this.makeGem(r,c,t);}}
    this.character=this.createPlayerCharacter(850,470,{physics:false,scale:.62,depth:80,anim:'think'});
    this.add.text(850,555,'DAVID’S MATCH LAB',{fontFamily:'Arial',fontSize:'13px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5).setDepth(100);
    this.add.text(480,568,'Click one gem, then an adjacent gem to swap · Match 3 or more',{fontFamily:'Arial',fontSize:'14px',color:'#c8d9e5'}).setOrigin(.5).setDepth(100);
  }
  randomTypeAvoidingMatch(r,c){let t;do{t=Phaser.Math.Between(0,this.types.length-1);}while((c>=2&&this.grid[r]?.[c-1]?.gemType===t&&this.grid[r]?.[c-2]?.gemType===t)||(r>=2&&this.grid[r-1]?.[c]?.gemType===t&&this.grid[r-2]?.[c]?.gemType===t));return t;}
  makeGem(r,c,type){const x=this.boardX+c*this.cell,y=this.boardY+r*this.cell;const g=this.add.container(x,y).setSize(44,44).setInteractive(new Phaser.Geom.Rectangle(-22,-22,44,44),Phaser.Geom.Rectangle.Contains).setDepth(5);const shadow=this.add.circle(3,5,19,0x000000,.26);const gem=this.add.star(0,0,6,10,20,this.colors[type],1).setStrokeStyle(3,0xffffff,.42);const shine=this.add.circle(-7,-8,4,0xffffff,.48);g.add([shadow,gem,shine]);g.row=r;g.col=c;g.gemType=type;g.on('pointerdown',()=>this.choose(g));return g;}
  choose(g){if(this.busy)return;if(!this.selected){this.selected=g;this.tweens.add({targets:g,scale:1.16,duration:90});return;}const a=this.selected;this.selected=null;this.tweens.add({targets:a,scale:1,duration:90});const adjacent=Math.abs(a.row-g.row)+Math.abs(a.col-g.col)===1;if(!adjacent){this.selected=g;this.tweens.add({targets:g,scale:1.16,duration:90});return;}this.swap(a,g,true);}
  swap(a,b,validate){this.busy=true;const ar=a.row,ac=a.col,br=b.row,bc=b.col;this.grid[ar][ac]=b;this.grid[br][bc]=a;a.row=br;a.col=bc;b.row=ar;b.col=ac;const ax=this.boardX+a.col*this.cell,ay=this.boardY+a.row*this.cell,bx=this.boardX+b.col*this.cell,by=this.boardY+b.row*this.cell;this.tweens.add({targets:a,x:ax,y:ay,duration:145,ease:'Quad.out'});this.tweens.add({targets:b,x:bx,y:by,duration:145,ease:'Quad.out',onComplete:()=>{const matches=this.findMatches();if(validate&&!matches.size){this.time.delayedCall(80,()=>this.swap(a,b,false));return;}if(matches.size)this.clearMatches(matches);else this.busy=false;}});}
  findMatches(){const out=new Set();for(let r=0;r<this.rows;r++){let run=[this.grid[r][0]];for(let c=1;c<=this.cols;c++){const cur=c<this.cols?this.grid[r][c]:null;if(cur&&cur.gemType===run[0].gemType)run.push(cur);else{if(run.length>=3)run.forEach(x=>out.add(x));run=cur?[cur]:[];}}}for(let c=0;c<this.cols;c++){let run=[this.grid[0][c]];for(let r=1;r<=this.rows;r++){const cur=r<this.rows?this.grid[r][c]:null;if(cur&&cur.gemType===run[0].gemType)run.push(cur);else{if(run.length>=3)run.forEach(x=>out.add(x));run=cur?[cur]:[];}}}return out;}
  clearMatches(matches){this.flashCharacter(this.character,'correct','think');const pts=matches.size*120;this.setScore(this.score+pts);for(const g of matches){this.grid[g.row][g.col]=null;for(let i=0;i<7;i++){const p=this.add.circle(g.x,g.y,Phaser.Math.Between(2,5),this.colors[g.gemType],1).setDepth(20);this.tweens.add({targets:p,x:g.x+Phaser.Math.Between(-36,36),y:g.y+Phaser.Math.Between(-36,36),alpha:0,duration:260,onComplete:()=>p.destroy()});}this.tweens.add({targets:g,scale:1.5,alpha:0,duration:160,onComplete:()=>g.destroy()});}this.time.delayedCall(190,()=>this.collapse());}
  collapse(){for(let c=0;c<this.cols;c++){let write=this.rows-1;for(let r=this.rows-1;r>=0;r--){const g=this.grid[r][c];if(g){if(r!==write){this.grid[write][c]=g;this.grid[r][c]=null;g.row=write;this.tweens.add({targets:g,y:this.boardY+write*this.cell,duration:180,ease:'Bounce.out'});}write--;}}for(let r=write;r>=0;r--){const t=Phaser.Math.Between(0,this.types.length-1);const g=this.makeGem(r,c,t);g.y=this.boardY-(write-r+1)*this.cell;this.grid[r][c]=g;this.tweens.add({targets:g,y:this.boardY+r*this.cell,duration:240,ease:'Bounce.out'});}}
    this.time.delayedCall(270,()=>{const again=this.findMatches();if(again.size){this.setScore(this.score+100);this.clearMatches(again);}else{this.busy=false;if(this.score>=2500)this.win('GEM CIRCUIT COMPLETE');}});
  }
}
